/// A type that can describe itself as a JSON Schema. Conformance is generated by `@Schemable`.
public protocol ADJSONSchemaProviding {
    /// The compiled schema describing this type. Built once and cached; safe to validate concurrently.
    static var jsonSchema: JSONSchema { get }

    /// SPI used by `@Schemable` to compose nested types into a parent's schema text. The double
    /// underscore signals "do not call directly" — use ``jsonSchema``.
    static var __adjsonSchemaText: String { get }
}

extension JSONSchema {
    /// A schema that accepts every instance. Serves as the non-throwing fallback for
    /// macro-generated schemas, whose text is well-formed by construction, so the generated
    /// ``ADJSONSchemaProviding/jsonSchema`` never traps and needs no `try` at the call site.
    public static let permitAll = JSONSchema(permitAll: ())

    // A boolean-`true` root accepts everything; validation never reads the document for such a
    // node, so an empty backing document is sufficient (and avoids parsing a constant).
    private init(permitAll: Void) {
        var root = SchemaNode()
        root.boolean = true
        self.nodes = [root]
        self.rootIndex = 0
        self.registry = [:]
        self.document = JSONDocument(backing: .bytes([]), tape: [])
    }
}

/// Generates a compiled JSON Schema for a `struct` from its stored properties, at compile time —
/// no instance and no `Mirror` reflection, unlike ``JSONSchema/describe(_:)``. Validate with
/// `T.jsonSchema`.
///
/// First cut: `struct`s whose stored properties have explicit type annotations. Scalars, arrays,
/// string-keyed dictionaries, and optionals map directly; nested custom types must also be
/// `@Schemable` so their schema can be composed into the parent. Types with custom `CodingKeys`,
/// and directly self-referential types, are left undescribed (a warning is emitted).
@attached(
    extension,
    conformances: ADJSONSchemaProviding,
    names: named(jsonSchema), named(__adjsonSchemaText), named(__adjsonSchemaCompiled)
)
public macro Schemable() = #externalMacro(module: "ADJSONMacros", type: "SchemableMacro")
